<a href="https://colab.research.google.com/github/Donalizasaji/LAB/blob/main/2348515_QC_Lab_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install qiskit


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 24.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.4/119.4 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 40.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 MB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.5/108.5 kB 3.6 MB/s eta 0:00:00


In [ ]:
import numpy as np
from qiskit.quantum_info import Statevector, Operator

In [ ]:


# 1. Tensor Product of Two Vectors

def tensor_product(vec1, vec2):
    return np.kron(vec1, vec2)

# Example vectors
psi = np.array([1, 0])  # |0⟩
phi = np.array([1/np.sqrt(2), 1/np.sqrt(2)])  # |+⟩

# Calculate the tensor product
result = tensor_product(psi, phi)
print("Tensor Product |ψ⟩ ⊗ |ϕ⟩:")
print(result)


Tensor Product |ψ⟩ ⊗ |ϕ⟩:
[0.70710678 0.70710678 0.         0.        ]


2. Create an Operator and Execute on State Vector

In [ ]:
# 2. Create an Operator and Execute on State Vector

# Define a simple operator (e.g., Pauli-X operator)
X_operator = np.array([[0, 1],
                       [1, 0]])

# Execute the operator on the state vector |ψ⟩
new_state = X_operator @ psi
print("\nNew State after applying X operator on |0⟩:")
print(new_state)


New State after applying X operator on |0⟩:
[0 1]


3. Partial Measurement

In [ ]:
# 3. Partial Measurement

def partial_measure(state, index):
    # For simplicity, we consider only measurement of a single qubit
    if index == 0:  # Measure the first qubit
        return np.array([state[0], state[2]]), np.array([state[1], state[3]])
    else:  # Measure the second qubit
        return np.array([state[0], state[1]]), np.array([state[2], state[3]])

# Get the measurement results
measured_0, measured_1 = partial_measure(result, 0)
print("\nPartial Measurement Results (Measurement on first qubit):")
print("Measured |0⟩ state:", measured_0)
print("Measured |1⟩ state:", measured_1)


Partial Measurement Results (Measurement on first qubit):
Measured |0⟩ state: [0.70710678 0.        ]
Measured |1⟩ state: [0.70710678 0.        ]


In [ ]:
# 4. CSWAP and Toffoli Gates

# CSWAP Gate
CSWAP = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 1, 0, 0],
                  [0, 0, 0, 0, 1, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 1],
                  [0, 0, 0, 0, 0, 0, 1, 0]])

print("\nCSWAP Matrix Representation:")
print(CSWAP)

# Toffoli Gate
Toffoli = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                    [0, 1, 0, 0, 0, 0, 0, 0],
                    [0, 0, 1, 0, 0, 0, 0, 0],
                    [0, 0, 0, 1, 0, 0, 0, 0],
                    [0, 0, 0, 0, 1, 0, 0, 0],
                    [0, 0, 0, 0, 0, 1, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0, 1],
                    [0, 0, 0, 0, 0, 0, 1, 0]])

print("\nToffoli Matrix Representation:")
print(Toffoli)



CSWAP Matrix Representation:
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]]

Toffoli Matrix Representation:
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]]


Tensor Product:

We define the function tensor_product using NumPy's kron function to compute the tensor product of two vectors.
Operator Application:

We define a simple Pauli-X operator and apply it to the |0⟩ state vector using matrix multiplication.
Partial Measurement:

The partial_measure function simulates measuring one of the qubits in the composite state.
Gate Representations:

The CSWAP and Toffoli gates are defined as 8x8 matrices to represent their action on 3 qubits.